modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower"
description = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"